<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CastRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CastRepository extends EntityRepository
{
    public function getMovies()
    {

    }

    public function getMoviesByRole()
    {

    }
}
